# Generated by Django 5.2.13 on 2026-04-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades_academicas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la carrera (ej: LCI, LDA)', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('duracion_anios', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='unidades_academicas.unidadacademica')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
    ]
